source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HaidoraDesignable_Example', :exclusive => true do
  pod "HaidoraDesignable", :path => "../"
end

target 'HaidoraDesignable_Tests', :exclusive => true do
  pod "HaidoraDesignable", :path => "../"

  
end
